import{useMemo,useState}from'react';import{inquiryMarkdown,routeInquiry,type Inquiry}from'./domain/route';import AiMode from'./AiMode';
const future=()=>{const d=new Date();d.setDate(d.getDate()+21);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};const sample:Inquiry={name:'Mira Hoffmann',email:'mira@example.com',destination:'Japan',origin:'Berlin',depart:future(),nights:12,travelers:2,tripType:'Luxury tailor-made',budget:'€12,000–€18,000',notes:'First visit to Japan. Interested in design hotels, food, a slower Kyoto stay, and a private guide for two days. Vegetarian preferences.'};
function App(){const[q,setQ]=useState<Inquiry>({...sample,destination:''});const[copied,setCopied]=useState(false);const route=useMemo(()=>routeInquiry(q),[q]);const set=(k:keyof Inquiry,v:string|number)=>setQ(x=>({...x,[k]:v}));async function copy(){await navigator.clipboard.writeText(inquiryMarkdown(q,route));setCopied(true);setTimeout(()=>setCopied(false),1800)}return <main>
<nav><a href="#top"><span>W</span>WAYFARE</a><p>Travel operations / Lab 09</p><button onClick={()=>setQ(sample)}>Load sample journey</button></nav>
<header id="top"><div className="route-art"><span className="sun"/><i className="path p1"/><i className="path p2"/><b className="pin one">BER</b><b className="pin two">TYO</b></div><div className="hero-copy"><span>INQUIRY → BRIEF → RIGHT DESK</span><h1>Every good journey<br/><em>starts with clarity.</em></h1><p>Collect the details once, create a useful travel brief, and route it to the team equipped to act.</p></div></header>
<AiMode app="travel-inquiry-router" payload={{inquiry:q,localResult:route}} label="Route inquiry with AI"/>
<section className="console"><div className="intake"><div className="step"><span>01</span><div><h2>Who is travelling?</h2><p>Contact and party context</p></div></div><div className="fields two"><label>Name<input value={q.name} onChange={e=>set('name',e.target.value)}/></label><label>Email<input type="email" value={q.email} onChange={e=>set('email',e.target.value)}/></label></div><div className="step"><span>02</span><div><h2>Shape the journey</h2><p>Route, timing, and party</p></div></div><div className="fields two"><label>From<input value={q.origin} onChange={e=>set('origin',e.target.value)} placeholder="Departure city"/></label><label>Destination<input value={q.destination} onChange={e=>set('destination',e.target.value)} placeholder="Country, city, or region"/></label><label>Departure<input type="date" value={q.depart} onChange={e=>set('depart',e.target.value)}/></label><label>Nights<input type="number" min="1" value={q.nights} onChange={e=>set('nights',Number(e.target.value))}/></label><label>Travelers<input type="number" min="1" value={q.travelers} onChange={e=>set('travelers',Number(e.target.value))}/></label><label>Trip style<select value={q.tripType} onChange={e=>set('tripType',e.target.value)}><option>Luxury tailor-made</option><option>Leisure package</option><option>Corporate retreat</option><option>Adventure & active</option></select></label></div><div className="step"><span>03</span><div><h2>Make it useful</h2><p>Preferences and commercial frame</p></div></div><label className="wide">Budget range<input value={q.budget} onChange={e=>set('budget',e.target.value)} placeholder="Total trip budget"/></label><label className="wide">Notes<textarea value={q.notes} onChange={e=>set('notes',e.target.value)} placeholder="Interests, pace, rooms, access, dietary needs…"/></label></div>
<aside className="route-card"><div className="card-top"><span>Live route recommendation</span><b className={route.priority.toLowerCase()}>{route.priority}</b></div><div className="ticket"><div className="ticket-route"><div><span>FROM</span><strong>{q.origin.slice(0,3).toUpperCase()||'TBC'}</strong><small>{q.origin||'Departure city'}</small></div><div className="flight"><i>✦</i></div><div><span>TO</span><strong>{q.destination.slice(0,3).toUpperCase()||'TBC'}</strong><small>{q.destination||'Destination'}</small></div></div><div className="ticket-meta"><div><span>DATE</span><b>{q.depart||'TBC'}</b></div><div><span>NIGHTS</span><b>{q.nights}</b></div><div><span>GUESTS</span><b>{q.travelers}</b></div></div></div><div className="routing"><span>Send to</span><h2>{route.desk}</h2><p>{route.workflow} has the strongest match for this inquiry.</p></div><div className="readiness"><div><span>Brief readiness</span><b>{route.requirements.length?`${4-route.requirements.length}/4`:'Ready'}</b></div>{route.requirements.length?<ul>{route.requirements.map(x=><li key={x}>Add {x.toLowerCase()}</li>)}</ul>:<p>✓ Core routing fields are complete</p>}</div><div className="summary"><span>Travel brief</span><p><b>{q.name||'Traveler'}</b> is planning a {q.nights}-night {q.tripType.toLowerCase()} journey to {q.destination||'a destination'} for {q.travelers} traveler{q.travelers===1?'':'s'}.</p><p>{q.notes||'Preferences still to be collected.'}</p></div><button onClick={copy}>{copied?'Brief copied':'Copy routed brief ↗'}</button><small>Routing support only. A travel specialist must validate availability, visas, safety, accessibility, pricing, and supplier fit.</small></aside></section>
<footer><span>Built by Jamil Darwish · Travel technology</span><span>No booking made · No inquiry submitted</span></footer></main>}
export default App;
